# Generated by Django 3.2.13 on 2023-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('JEWELRY', 'Jewelry')], default='ELECTRONICS', max_length=17)),
                ('address', models.CharField(max_length=200)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
